<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Add' => 'Добавить',
  'Delte from cart' => 'Удалить с корзины',
  'Remove' => 'Удалить',
  'Delete' => 'Удалить',
  'Delivery price:' => 'Стоимость доставки:',
  'Image' => 'Изображение',
  'In your cart <strong>{n}</strong>' => 'В вашей корзине <strong>{n}</strong>',
  'Make order' => 'Оформить заказ',
  'Q-ty' => 'Кол-во',
  'Resume' => 'Продолжить покупки',
  'Sub-Total:' => 'Цена за товары:',
  'Summ' => 'Сума',
  'Title' => 'Название',
  'Total price:' => 'Итоговая цена:',
  'You cart is empty' => 'Ваша корзина пуста',
  'n==1#item|n>1#items' => 'n==0#товаров|n==1#товар|n<5#товара|n>4#товаров',
);
