<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Set the percent quantity from -100 to +infinity.' => 'Установите размер изменения цен. В диапазоне от -100% до +бесконечность %.',
  'Categories' => 'Категории',
  'Do u sure that u want yo change global price?' => 'Вы уверены что хотите изменить цены глобально?',
  'Global Price Change' => 'Глобальное измениение цен',
  'Percents' => 'Проценты',
  'Update all prices' => 'Изменить все цены',
  'You cannot reduce price more than -100%' => 'Вы не можете изменить цену более чем на -100%',
);
