<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Product "{product}" already exists in this order' => '',
  'Product had not been deleted from order' => '',
  'Product not found' => '',
  'Product succesfully deleted from order' => '',
  'Such product does not exist in current order' => '',
  '-= Select category =-' => '-= Выберите категорию =-',
  'Add product to order' => 'Добавить товар к заказу',
  'Create order' => 'Создать заказ',
  'Decrement' => 'Уменьшить',
  'Edit order' => 'Редактировать заказ',
  'Increment' => 'Увеличить',
  'Number of products' => 'Кол-во',
  'Order is alreadey excuted. You cannot change it.' => 'Заказ уже выполнен. Вы не можете его изменить.',
  'Order not found' => 'Заказ не найден',
  'Order products' => 'Товары',
  'Orders' => 'Заказы',
  'Product price' => 'Цена',
  'Save' => 'Сохранить',
  'Save and add products' => 'Сохранить и добавить товары',
  'Subtotal price' => 'Сумма',
  'View order' => 'Посмотреть заказ',
  'You cannot delete executed order' => 'Вы не можете удалить выполненый заказ',
);
