<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'New user has been created succesfully.' => '',
  'User data had been updated succesfully.' => '',
  'Add user' => 'Новый пользователь',
  'Create user' => 'Создать пользователя',
  'Edit user' => 'Редактировать пользователя',
  'Field "{attribute}" must consist letters and numbers only.' => 'Поле "{attribute}" должно состоять только из цифр и букв.',
  'New password' => 'Новый пароль',
  'New password confirm' => 'Повторите новый пароль',
  'Old password' => 'Старый пароль',
  'Old password is incorret.' => 'Старый пароль введен не правильно',
  'Password changed succesfully.' => 'Пароль изменен успешно.',
  'Profile' => 'Мой профиль',
  'Users' => 'Пользователи',
  'Your profile updated succesfully.' => 'Профиль обновлен успешно.',
);
