<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Administration' => '',
  'Are you sure you want to delete this item?' => '',
  'CSV' => '',
  'Changes saved.' => '',
  'Changes saved. You can add a new entry.' => '',
  'Choose {name}' => '',
  'Could not create folder "{dir}". Make sure "uploads" folder is writable.' => '',
  'Could not create upload folder "{dir}".' => '',
  'Could not delete entry "{name}" with an ID "{pk}".' => '',
  'Could not load model "{name}".' => '',
  'Could not save file or file exists: "{file}".' => '',
  'Could not upload file.' => '',
  'Create' => '',
  'Create {name}' => '',
  'Delete' => '',
  'Download' => '',
  'Download {name}' => '',
  'Edit {name}' => '',
  'Error' => '',
  'Excel' => '',
  'Home' => '',
  'Image' => '',
  'Image preview' => '',
  'Incorrect username or password.' => '',
  'Invalid file extension "{ext}".' => '',
  'List' => '',
  'Login' => '',
  'Logout' => '',
  'MS CSV' => '',
  'Password' => '',
  'Please enter your username and password.' => '',
  'Preview' => '',
  'Remember me next time' => '',
  'Save' => '',
  'Save and add another' => '',
  'Save and continue editing' => '',
  'Username' => '',
);
