<?php

return array(
    array(
        'category_id' => 1,
        'title' => 'НАСОСЫ ДЛЯ ЗАПРАВКИ И ПЕРЕКАЧКИ ДТ',
        'url' => 'nasosu-dlia-pereka4ki-i-zapravki-dt',
        'status' => '1',
        'description' => '<p>НАСОСЫ ДЛЯ ЗАПРАВКИ И ПЕРЕКАЧКИ ДТ</p>',
        'language_id' => 1,
    ),
    array(
        'category_id' => 2,
        'title' => 'НАСОСЫ ДЛЯ ЗАПРАВКИ И ПЕРЕКАЧКИ БЕНЗИНА',
        'url' => 'nasosu-dlia-pereka4ki-i-zapravki-benzina',
        'status' => '1',
        'description' => '<p>НАСОСЫ ДЛЯ ЗАПРАВКИ И ПЕРЕКАЧКИ БЕНЗИНА</p>',
        'language_id' => 1,
    ),
    array(
        'category_id' => 3,
        'title' => 'ЗАПРАВОЧНЫЕ КОЛОНКИ ДЛЯ ДТ',
        'url' => 'zapravochnue-kolonki-dlia-dt',
        'status' => '1',
        'description' => '<p>ЗАПРАВОЧНЫЕ КОЛОНКИ ДЛЯ ДТ</p>',
        'language_id' => 1,
    ),
    array(
        'category_id' => 4,
        'title' => 'НАСОСИ ДЛЯ ЗАПРАВКИ і перекачування ДТ',
        'url' => 'nasosu-dlia-pereka4ki-i-zapravki-dt',
        'status' => '1',
        'description' => '<p>НАСОСИ ДЛЯ ЗАПРАВКИ і перекачування ДТ</p>',
        'language_id' => 2,
    ),
    array(
        'category_id' => 5,
        'title' => 'НАСОСИ ДЛЯ ЗАПРАВКИ І перекачування бензину',
        'url' => 'nasosu-dlia-pereka4ki-i-zapravki-benzina',
        'status' => '1',
        'description' => '<p>НАСОСИ ДЛЯ ЗАПРАВКИ І перекачування бензину</p>',
        'language_id' => 2,
    ),
    array(
        'category_id' => 6,
        'title' => 'ЗАПРАВНІ КОЛОНКИ ДЛЯ ДТ',
        'url' => 'zapravochnue-kolonki-dlia-dt',
        'status' => '1',
        'description' => '<p>ЗАПРАВНІ КОЛОНКИ ДЛЯ ДТ</p>',
        'language_id' => 2,
    ),
    array(
        'category_id' => 7,
        'parent_category_id' => 1,
        'title' => 'Subcategory 1',
        'url' => 'subcategory-1',
        'status' => '1',
        'description' => '<p>subcategory1</p>',
        'language_id' => 1,
    ),
    array(
        'category_id' => 8,
        'parent_category_id' => 1,
        'title' => 'Subcategory 2',
        'url' => 'subcategory-2',
        'status' => '1',
        'description' => '<p>subcategory2</p>',
        'language_id' => 1,
    ),
    array(
        'category_id' => 9,
        'parent_category_id' => 1,
        'title' => 'Subcategory 3',
        'url' => 'subcategory-3',
        'status' => '1',
        'description' => '<p>subcategory3</p>',
        'language_id' => 1,
    ),
    array(
        'category_id' => 10,
        'parent_category_id' => 4,
        'title' => 'Subcategory 4',
        'url' => 'subcategory-4',
        'status' => '1',
        'description' => '<p>subcategory4</p>',
        'language_id' => 2,
    ),
    array(
        'category_id' => 11,
        'parent_category_id' => 4,
        'title' => 'Subcategory 5',
        'url' => 'subcategory-5',
        'status' => '1',
        'description' => '<p>subcategory5</p>',
        'language_id' => 2,
    ),
    array(
        'category_id' => 12,
        'parent_category_id' => 4,
        'title' => 'Subcategory 6',
        'url' => 'subcategory-6',
        'status' => '1',
        'description' => '<p>subcategory6</p>',
        'language_id' => 2,
    ),
);
