<?php

return array(
    // Russian
    // НАСОСЫ ДЛЯ ЗАПРАВКИ И ПЕРЕКАЧКИ ДТ
    array(
        'category_id' => 1,
        'language_id' => 1,
        'parent_category_id' => 0,
        'title' => 'НАСОСЫ ДЛЯ ЗАПРАВКИ И ПЕРЕКАЧКИ ДТ',
        'url' => 'nasosy-dlya-zapravki-i-pereka4ki-dt',
        'prom_id' => 65059,
        'prom_parent_id' => 0,
    ),
    array(
        'category_id' => 2,
        'language_id' => 1,
        'parent_category_id' => 1,
        'title' => '12/24 Вольт',
        'url' => '1224-volt',
        'prom_id' => 101413,
        'prom_parent_id' => 65059,
    ),
    array(
        'category_id' => 3,
        'language_id' => 1,
        'parent_category_id' => 1,
        'title' => '220 Вольт',
        'url' => '220-volt',
        'prom_id' => 101414,
        'prom_parent_id' => 65059,
    ),
    array(
        'category_id' => 4,
        'language_id' => 1,
        'parent_category_id' => 1,
        'title' => 'Насосы для бочки',
        'url' => 'nasosy-dlya-bochki',
        'prom_id' => 85148,
        'prom_parent_id' => 65059,
    ),
    array(
        'category_id' => 5,
        'language_id' => 1,
        'parent_category_id' => 1,
        'title' => 'Заправочные колонки',
        'url' => 'zapravochnye-kolonki',
        'prom_id' => 85146,
        'prom_parent_id' => 65059,
    ),
    array(
        'category_id' => 6,
        'language_id' => 1,
        'parent_category_id' => 1,
        'title' => 'Насос на дрель',
        'url' => 'nasos-drel',
        'prom_id' => 441267,
        'prom_parent_id' => 65059,
    ),
    array(
        'category_id' => 7,
        'language_id' => 1,
        'parent_category_id' => 0,
        'title' => 'НАСОСЫ ДЛЯ ЗАПРАВКИ И ПЕРЕКАЧКИ БЕНЗИНА',
        'url' => 'nasosy-dlya-zapravki-ipereka4ki-benzina',
        'prom_id' => 65068,
        'prom_parent_id' => 65068,
    ),
    array(
        'category_id' => 8,
        'language_id' => 1,
        'parent_category_id' => 7,
        'title' => '12/24 Вольт',
        'url' => '1224-volt',
        'prom_id' => 237606,
        'prom_parent_id' => 65068,
    ),
    array(
        'category_id' => 9,
        'language_id' => 1,
        'parent_category_id' => 7,
        'title' => '220 Вольт',
        'url' => '220-volt',
        'prom_id' => 237607,
        'prom_parent_id' => 65068,
    ),
    array(
        'category_id' => 10,
        'language_id' => 1,
        'parent_category_id' => 0,
        'title' => 'ЗАПРАВОЧНЫЕ КОЛОНКИ ДЛЯ ДТ ',
        'url' => 'zapravochnye-kolonki-dlya-dt',
        'prom_id' => 2329108,
        'prom_parent_id' => 0,
    ),
    array(
        'category_id' => 11,
        'language_id' => 1,
        'parent_category_id' => 10,
        'title' => '12/24 Вольт',
        'url' => '1224-volt',
        'prom_id' => 2329198,
        'prom_parent_id' => 2329108,
    ),
    array(
        'category_id' => 12,
        'language_id' => 1,
        'parent_category_id' => 10,
        'title' => '220 Вольт',
        'url' => '220-volt',
        'prom_id' => 2329200,
        'prom_parent_id' => 2329108,
    ),
    //ЗАПРАВОЧНЫЕ КОЛОНКИ ДЛЯ БЕНЗИНА
    array(
        'category_id' => 13,
        'language_id' => 1,
        'parent_category_id' => 0,
        'title' => 'ЗАПРАВОЧНЫЕ КОЛОНКИ ДЛЯ БЕНЗИНА',
        'url' => 'zapravochnye-kolonki-dlya-benzina',
        'prom_id' => 2329120,
        'prom_parent_id' => 0,
    ),
    array(
        'category_id' => 14,
        'language_id' => 1,
        'parent_category_id' => 13,
        'title' => '12/24 Вольт',
        'url' => '1224-volt',
        'prom_id' => 2329138,
        'prom_parent_id' => 2329120,
    ),
    array(
        'category_id' => 15,
        'language_id' => 1,
        'parent_category_id' => 13,
        'title' => '220 Вольт',
        'url' => '220-volt',
        'prom_id' => 2329139,
        'prom_parent_id' => 2329120,
    ),
    //НАСОСЫ ДЛЯ ПЕРЕКАЧКИ МАСЛА
    array(
        'category_id' => 16,
        'language_id' => 1,
        'parent_category_id' => 0,
        'title' => 'НАСОСЫ ДЛЯ ПЕРЕКАЧКИ МАСЛА',
        'url' => 'nasosy-dlya-perekachki-masla',
        'prom_id' => 85171,
        'prom_parent_id' => 0,
    ),
    //ПИСТОЛЕТЫ ТОПЛИВОРАЗДАТОЧНЫЕ И АКСЕССУАРЫ 
    array(
        'category_id' => 17,
        'language_id' => 1,
        'parent_category_id' => 0,
        'title' => 'ПИСТОЛЕТЫ ТОПЛИВОРАЗДАТОЧНЫЕ И АКСЕССУАРЫ',
        'url' => 'pistolety-toplivorazdatochnye-aksessuary',
        'prom_id' => 65814,
        'prom_parent_id' => 0,
    ),
    array(
        'category_id' => 18,
        'language_id' => 1,
        'parent_category_id' => 17,
        'title' => 'Ремкомплекты',
        'url' => 'remkomplekty',
        'prom_id' => 378122,
        'prom_parent_id' => 65814,
    ),
    array(
        'category_id' => 19,
        'language_id' => 1,
        'parent_category_id' => 17,
        'title' => 'Топливные пистолеты',
        'url' => 'toplivnye-pistolety',
        'prom_id' => 2405462,
        'prom_parent_id' => 65814,
    ),
    array(
        'category_id' => 20,
        'language_id' => 1,
        'parent_category_id' => 17,
        'title' => 'Соединения',
        'url' => 'soedineniya',
        'prom_id' => 2405592,
        'prom_parent_id' => 65814,
    ),
    //СЧЕТЧИКИ УЧЕТА ТОПЛИВА 
    array(
        'category_id' => 21,
        'language_id' => 1,
        'parent_category_id' => 0,
        'title' => 'СЧЕТЧИКИ УЧЕТА ТОПЛИВА',
        'url' => 'schetchiki-ucheta-topliva',
        'prom_id' => 65646,
        'prom_parent_id' => 0,
    ),
    //РУЧНЫЕ НАСОСЫ
    array(
        'category_id' => 22,
        'language_id' => 1,
        'parent_category_id' => 0,
        'title' => 'РУЧНЫЕ НАСОСЫ',
        'url' => 'ruchnye-nasosy',
        'prom_id' => 98658,
        'prom_parent_id' => 0,
    ),
    //НАСОСЫ ДЛЯ ПЕРЕКАЧКИ Adblue 
    array(
        'category_id' => 23,
        'language_id' => 1,
        'parent_category_id' => 0,
        'title' => 'НАСОСЫ ДЛЯ ПЕРЕКАЧКИ Adblue',
        'url' => 'nasosy-dlya-perekachki-adblue',
        'prom_id' => 1474862,
        'prom_parent_id' => 0,
    ),
    //МОБИЛЬНЫЙ ЗАПРАВОЧНЫЙ МОДУЛЬ (МИНИ АЗС) 
    array(
        'category_id' => 24,
        'language_id' => 1,
        'parent_category_id' => 0,
        'title' => 'МОБИЛЬНЫЙ ЗАПРАВОЧНЫЙ МОДУЛЬ (МИНИ АЗС)',
        'url' => 'mobilnyj-zapravochnyj-modul',
        'prom_id' => 102495,
        'prom_parent_id' => 0,
    ),
    //ФИЛЬТРЫ ТОНКОЙ ОЧИСТКИ ТОПЛИВА 
    array(
        'category_id' => 25,
        'language_id' => 1,
        'parent_category_id' => 0,
        'title' => 'ФИЛЬТРЫ ТОНКОЙ ОЧИСТКИ ТОПЛИВА',
        'url' => 'filtry-tonkoj-ochistki',
        'prom_id' => 106882,
        'prom_parent_id' => 0,
    ),
    array(
        'category_id' => 26,
        'language_id' => 1,
        'parent_category_id' => 25,
        'title' => 'Максимальный проток топлива до 65 л/мин',
        'url' => 'maksimalnyj-protok-topliva-65-lpm',
        'prom_id' => 234301,
        'prom_parent_id' => 106882,
    ),
    array(
        'category_id' => 27,
        'language_id' => 1,
        'parent_category_id' => 25,
        'title' => 'Фильтры сепараторы тонкой очистки топлива Gespasa',
        'url' => 'filtry-separatornoy-tonkoy-ochistki-topliva',
        'prom_id' => 295167,
        'prom_parent_id' => 106882,
    ),
    array(
        'category_id' => 65,
        'language_id' => 1,
        'parent_category_id' => 25,
        'title' => 'Максимальный проток топлива до 120 л/мин.',
        'url' => 'maksimalnyj-protok-topliva-120-lpm',
        'prom_id' => 234302,
        'prom_parent_id' => 106882,
    ),
    array(
        'category_id' => 28,
        'language_id' => 1,
        'parent_category_id' => 25,
        'title' => 'Максимальный проток топлива до 150 л/мин.',
        'url' => 'maksimalnyj-protok-topliva-do-15-lpm',
        'prom_id' => 2396509,
        'prom_parent_id' => 106882,
    ),
    //Электронная система учета топлива Gespasa 
    array(
        'category_id' => 29,
        'language_id' => 1,
        'parent_category_id' => 0,
        'title' => 'Электронная система учета топлива Gespasa',
        'url' => 'elektronnaya-sistema-ucheta',
        'prom_id' => 238153,
        'prom_parent_id' => 0,
    ),
    //Промышленные клеи, герметики, смазки Loxeal (Локсеаль)
    array(
        'category_id' => 30,
        'language_id' => 1,
        'parent_category_id' => 0,
        'title' => 'Промышленные клеи, герметики, смазки Loxeal (Локсеаль)',
        'url' => 'promyshlennye-klei-germetiki',
        'prom_id' => 788319,
        'prom_parent_id' => 0,
    ),
    //СЧЕТЧИКИ РАСХОДА НА ДВИГАТЕЛЬ 
    array(
        'category_id' => 31,
        'language_id' => 1,
        'parent_category_id' => 0,
        'title' => 'СЧЕТЧИКИ РАСХОДА НА ДВИГАТЕЛЬ',
        'url' => 'schetchiki-rashoda-dvigatel',
        'prom_id' => 2248966,
        'prom_parent_id' => 0,
    ),
    //GPS МОНИТОРИНГ ТРАНСПОРТА
    array(
        'category_id' => 32,
        'language_id' => 1,
        'parent_category_id' => 0,
        'title' => 'GPS МОНИТОРИНГ ТРАНСПОРТА',
        'url' => 'gps-monitoring-transporta',
        'prom_id' => 2247902,
        'prom_parent_id' => 0,
    ),
    // UKRAINIAN
    array(
        'category_id' => 33,
        'language_id' => 2,
        'parent_category_id' => 0,
        'title' => 'НАСОСЫ ДЛЯ ЗАПРАВКИ И ПЕРЕКАЧКИ ДТ',
        'url' => 'nasosy-dlya-zapravki-i-pereka4ki-dt',
        'prom_id' => 65059,
        'prom_parent_id' => 0,
    ),
    array(
        'category_id' => 34,
        'language_id' => 2,
        'parent_category_id' => 33,
        'title' => '12/24 Вольт',
        'url' => '1224-volt',
        'prom_id' => 101413,
        'prom_parent_id' => 65059,
    ),
    array(
        'category_id' => 35,
        'language_id' => 2,
        'parent_category_id' => 33,
        'title' => '220 Вольт',
        'url' => '220-volt',
        'prom_id' => 101414,
        'prom_parent_id' => 65059,
    ),
    array(
        'category_id' => 36,
        'language_id' => 2,
        'parent_category_id' => 33,
        'title' => 'Насосы для бочки',
        'url' => 'nasosy-dlya-bochki',
        'prom_id' => 85148,
        'prom_parent_id' => 65059,
    ),
    array(
        'category_id' => 37,
        'language_id' => 2,
        'parent_category_id' => 33,
        'title' => 'Заправочные колонки',
        'url' => 'zapravochnye-kolonki',
        'prom_id' => 85146,
        'prom_parent_id' => 65059,
    ),
    array(
        'category_id' => 38,
        'language_id' => 2,
        'parent_category_id' => 33,
        'title' => 'Насос на дрель',
        'url' => 'nasos-drel',
        'prom_id' => 441267,
        'prom_parent_id' => 65059,
    ),
    array(
        'category_id' => 39,
        'language_id' => 2,
        'parent_category_id' => 0,
        'title' => 'НАСОСЫ ДЛЯ ЗАПРАВКИ И ПЕРЕКАЧКИ БЕНЗИНА',
        'url' => 'nasosy-dlya-zapravki-ipereka4ki-benzina',
        'prom_id' => 65068,
        'prom_parent_id' => 65068,
    ),
    array(
        'category_id' => 40,
        'language_id' => 2,
        'parent_category_id' => 39,
        'title' => '12/24 Вольт',
        'url' => '1224-volt',
        'prom_id' => 237606,
        'prom_parent_id' => 65068,
    ),
    array(
        'category_id' => 41,
        'language_id' => 2,
        'parent_category_id' => 39,
        'title' => '220 Вольт',
        'url' => '220-volt',
        'prom_id' => 237607,
        'prom_parent_id' => 65068,
    ),
    array(
        'category_id' => 42,
        'language_id' => 2,
        'parent_category_id' => 0,
        'title' => 'ЗАПРАВОЧНЫЕ КОЛОНКИ ДЛЯ ДТ ',
        'url' => 'zapravochnye-kolonki-dlya-dt',
        'prom_id' => 2329108,
        'prom_parent_id' => 0,
    ),
    array(
        'category_id' => 43,
        'language_id' => 2,
        'parent_category_id' => 42,
        'title' => '12/24 Вольт',
        'url' => '1224-volt',
        'prom_id' => 2329198,
        'prom_parent_id' => 2329108,
    ),
    array(
        'category_id' => 44,
        'language_id' => 2,
        'parent_category_id' => 42,
        'title' => '220 Вольт',
        'url' => '220-volt',
        'prom_id' => 2329200,
        'prom_parent_id' => 2329108,
    ),
    //ЗАПРАВОЧНЫЕ КОЛОНКИ ДЛЯ БЕНЗИНА
    array(
        'category_id' => 45,
        'language_id' => 2,
        'parent_category_id' => 0,
        'title' => 'ЗАПРАВОЧНЫЕ КОЛОНКИ ДЛЯ БЕНЗИНА',
        'url' => 'zapravochnye-kolonki-dlya-benzina',
        'prom_id' => 2329120,
        'prom_parent_id' => 0,
    ),
    array(
        'category_id' => 46,
        'language_id' => 2,
        'parent_category_id' => 45,
        'title' => '12/24 Вольт',
        'url' => '1224-volt',
        'prom_id' => 2329138,
        'prom_parent_id' => 2329120,
    ),
    array(
        'category_id' => 47,
        'language_id' => 2,
        'parent_category_id' => 45,
        'title' => '220 Вольт',
        'url' => '220-volt',
        'prom_id' => 2329139,
        'prom_parent_id' => 2329120,
    ),
    //НАСОСЫ ДЛЯ ПЕРЕКАЧКИ МАСЛА
    array(
        'category_id' => 48,
        'language_id' => 2,
        'parent_category_id' => 0,
        'title' => 'НАСОСЫ ДЛЯ ПЕРЕКАЧКИ МАСЛА',
        'url' => 'nasosy-dlya-perekachki-masla',
        'prom_id' => 85171,
        'prom_parent_id' => 0,
    ),
    //ПИСТОЛЕТЫ ТОПЛИВОРАЗДАТОЧНЫЕ И АКСЕССУАРЫ 
    array(
        'category_id' => 49,
        'language_id' => 2,
        'parent_category_id' => 0,
        'title' => 'ПИСТОЛЕТЫ ТОПЛИВОРАЗДАТОЧНЫЕ И АКСЕССУАРЫ',
        'url' => 'pistolety-toplivorazdatochnye-aksessuary',
        'prom_id' => 65814,
        'prom_parent_id' => 0,
    ),
    array(
        'category_id' => 50,
        'language_id' => 2,
        'parent_category_id' => 49,
        'title' => 'Ремкомплекты',
        'url' => 'remkomplekty',
        'prom_id' => 378122,
        'prom_parent_id' => 65814,
    ),
    array(
        'category_id' => 51,
        'language_id' => 2,
        'parent_category_id' => 49,
        'title' => 'Топливные пистолеты',
        'url' => 'toplivnye-pistolety',
        'prom_id' => 2405462,
        'prom_parent_id' => 65814,
    ),
    array(
        'category_id' => 52,
        'language_id' => 2,
        'parent_category_id' => 49,
        'title' => 'Соединения',
        'url' => 'soedineniya',
        'prom_id' => 2405592,
        'prom_parent_id' => 65814,
    ),
    //СЧЕТЧИКИ УЧЕТА ТОПЛИВА 
    array(
        'category_id' => 53,
        'language_id' => 2,
        'parent_category_id' => 0,
        'title' => 'СЧЕТЧИКИ УЧЕТА ТОПЛИВА',
        'url' => 'schetchiki-ucheta-topliva',
        'prom_id' => 65646,
        'prom_parent_id' => 0,
    ),
    //РУЧНЫЕ НАСОСЫ
    array(
        'category_id' => 54,
        'language_id' => 2,
        'parent_category_id' => 0,
        'title' => 'РУЧНЫЕ НАСОСЫ',
        'url' => 'ruchnye-nasosy',
        'prom_id' => 98658,
        'prom_parent_id' => 0,
    ),
    //НАСОСЫ ДЛЯ ПЕРЕКАЧКИ Adblue 
    array(
        'category_id' => 55,
        'language_id' => 2,
        'parent_category_id' => 0,
        'title' => 'НАСОСЫ ДЛЯ ПЕРЕКАЧКИ Adblue',
        'url' => 'nasosy-dlya-perekachki-adblue',
        'prom_id' => 1474862,
        'prom_parent_id' => 0,
    ),
    //МОБИЛЬНЫЙ ЗАПРАВОЧНЫЙ МОДУЛЬ (МИНИ АЗС) 
    array(
        'category_id' => 56,
        'language_id' => 2,
        'parent_category_id' => 0,
        'title' => 'МОБИЛЬНЫЙ ЗАПРАВОЧНЫЙ МОДУЛЬ (МИНИ АЗС)',
        'url' => 'mobilnyj-zapravochnyj-modul',
        'prom_id' => 102495,
        'prom_parent_id' => 0,
    ),
    //ФИЛЬТРЫ ТОНКОЙ ОЧИСТКИ ТОПЛИВА 
    array(
        'category_id' => 57,
        'language_id' => 2,
        'parent_category_id' => 0,
        'title' => 'ФИЛЬТРЫ ТОНКОЙ ОЧИСТКИ ТОПЛИВА',
        'url' => 'filtry-tonkoj-ochistki',
        'prom_id' => 106882,
        'prom_parent_id' => 0,
    ),
    array(
        'category_id' => 58,
        'language_id' => 2,
        'parent_category_id' => 57,
        'title' => 'Максимальный проток топлива до 65 л/мин',
        'url' => 'maksimalnyj-protok-topliva-65-lpm',
        'prom_id' => 234301,
        'prom_parent_id' => 106882,
    ),
    array(
        'category_id' => 59,
        'language_id' => 2,
        'parent_category_id' => 57,
        'title' => 'Фильтры сепараторы тонкой очистки топлива Gespasa',
        'url' => 'filtry-separatornoy-tonkoy-ochistki-topliva',
        'prom_id' => 295167,
        'prom_parent_id' => 106882,
    ),
    array(
        'category_id' => 66,
        'language_id' => 2,
        'parent_category_id' => 57,
        'title' => 'Максимальный проток топлива до 120 л/мин.',
        'url' => 'maksimalnyj-protok-topliva-120-lpm',
        'prom_id' => 234302,
        'prom_parent_id' => 106882,
    ),
    array(
        'category_id' => 60,
        'language_id' => 2,
        'parent_category_id' => 57,
        'title' => 'Максимальный проток топлива до 150 л/мин.',
        'url' => 'maksimalnyj-protok-topliva-do-15-lpm',
        'prom_id' => 2396509,
        'prom_parent_id' => 106882,
    ),
    //Электронная система учета топлива Gespasa 
    array(
        'category_id' => 61,
        'language_id' => 2,
        'parent_category_id' => 0,
        'title' => 'Электронная система учета топлива Gespasa',
        'url' => 'elektronnaya-sistema-ucheta',
        'prom_id' => 238153,
        'prom_parent_id' => 0,
    ),
    //Промышленные клеи, герметики, смазки Loxeal (Локсеаль)
    array(
        'category_id' => 62,
        'language_id' => 2,
        'parent_category_id' => 0,
        'title' => 'Промышленные клеи, герметики, смазки Loxeal (Локсеаль)',
        'url' => 'promyshlennye-klei-germetiki',
        'prom_id' => 788319,
        'prom_parent_id' => 0,
    ),
    //СЧЕТЧИКИ РАСХОДА НА ДВИГАТЕЛЬ 
    array(
        'category_id' => 63,
        'language_id' => 2,
        'parent_category_id' => 0,
        'title' => 'СЧЕТЧИКИ РАСХОДА НА ДВИГАТЕЛЬ',
        'url' => 'schetchiki-rashoda-dvigatel',
        'prom_id' => 2248966,
        'prom_parent_id' => 0,
    ),
    //GPS МОНИТОРИНГ ТРАНСПОРТА
    array(
        'category_id' => 64,
        'language_id' => 2,
        'parent_category_id' => 0,
        'title' => 'GPS МОНИТОРИНГ ТРАНСПОРТА',
        'url' => 'gps-monitoring-transporta',
        'prom_id' => 2247902,
        'prom_parent_id' => 0,
    ),
);
