<?php

return array(
    array(
        'key' => 'company',
        'title' => 'Название компании',
        'value' => 'Компания',
        'language_id' => 1,
    ),
    array(
        'key' => 'title',
        'title' => 'Заголовок (Title)',
        'value' => 'Компания',
        'language_id' => 1,
    ),
    array(
        'key' => 'meta_keywords',
        'title' => 'Ключевые слова (meta)',
        'value' => 'keyword1, keyword2, keyword3',
        'language_id' => 1,
    ),
    array(
        'key' => 'meta_description',
        'title' => 'Описание (meta)',
        'value' => 'Some description...',
        'language_id' => 1,
    ),
    array(
        'key' => 'admin_email',
        'title' => 'E-Mail администратора',
        'value' => 'admin@exaple.com',
        'language_id' => 1,
    ),
    array(
        'key' => 'company',
        'title' => 'Назва компанії',
        'value' => 'Компания',
        'language_id' => 2,
    ),
    array(
        'key' => 'title',
        'title' => 'Заголовок (Title)',
        'value' => 'Компанія петролайн',
        'language_id' => 2,
    ),
    array(
        'key' => 'meta_keywords',
        'title' => 'Ключові слова (meta)',
        'value' => 'keyword1, keyword2, keyword3',
        'language_id' => 2,
    ),
    array(
        'key' => 'meta_description',
        'title' => 'Описание (meta)',
        'value' => 'Мета ... дескріпшн',
        'language_id' => 2,
    ),
    array(
        'key' => 'admin_email',
        'title' => 'E-Mail администратора',
        'value' => 'admin@exaple.com',
        'language_id' => 2,
    ),
    array(
        'key' => 'about_us',
        'title' => 'Страница о нас',
        'value' => '',
        'language_id' => 1,
        'widget' => 'tinymce',
    ),
    array(
        'key' => 'about_us_title',
        'title' => 'Заголовок (Страница о нас)',
        'value' => '',
        'language_id' => 1,
    ),
    array(
        'key' => 'about_us',
        'title' => 'Сторінка про нас',
        'value' => '',
        'language_id' => 2,
        'widget' => 'tinymce',
    ),
    array(
        'key' => 'about_us_title',
        'title' => 'Заголовок (Сторінка про нас)',
        'value' => '',
        'language_id' => 2,
    ),
    array(
        'key' => 'delivery_payment',
        'title' => 'Оплата и доставка',
        'value' => '',
        'language_id' => 1,
        'widget' => 'tinymce',
    ),
    array(
        'key' => 'delivery_payment_title',
        'title' => 'Заголовок (Оплата и доставка)',
        'value' => '',
        'language_id' => 1,
    ),
    array(
        'key' => 'delivery_payment',
        'title' => 'Оплата та доставка',
        'value' => '',
        'language_id' => 2,
        'widget' => 'tinymce',
    ),
    array(
        'key' => 'delivery_payment_title',
        'title' => 'Заголовок (Оплата та доставка)',
        'value' => '',
        'language_id' => 2,
    ),
    array(
        'key' => 'contacts',
        'title' => 'Контакты',
        'value' => '',
        'language_id' => 1,
        'widget' => 'tinymce',
    ),
    array(
        'key' => 'contacts_title',
        'title' => 'Заголовок (Контакты)',
        'value' => '',
        'language_id' => 1,
    ),
    array(
        'key' => 'contacts',
        'title' => 'Контакти',
        'value' => '',
        'language_id' => 2,
        'widget' => 'tinymce',
    ),
    array(
        'key' => 'contacts_title',
        'title' => 'Заголовок (Контакти)',
        'value' => '',
        'language_id' => 2,
    ),
);