<?php

return array(
    array(
        'product_id' => 1,
        'category_id' => 1,
        'url' => 'nasos-dlia-dizelnogo-topliva-krt-12v-50lpm',
        'title' => 'Насос для дизельного топлива KPT: 12 В, 40 л/мин',
        //'description' => 'TEXT NOT NULL',
        'price' => 1580,
        //'trade_price' => 'DECIMAL(8,2)',
        //'min_trade_order' => 'SMALLINT UNSIGNED',
        //'meta_title' => 'VARCHAR(100)',
        //'meta_description' => 'TEXT',
        //'meta_keywords' => 'TEXT',
        'created_at' => new CDbException('NOW()'),
        'updated_at' => new CDbException('NOW()'),
        'created_by' => 1,
        'updated_by' => 1,
    ),
    array(
        'product_id' => 2,
        'category_id' => 1,
        'url' => 'nasos-dlia-pereka4ki-dizelnogo-topliva-ecokit-12v-40lpm',
        'title' => 'Насос для перекачки дизельного топлива ECOKIT, 12В, 40 л/мин',
        //'description' => 'TEXT NOT NULL',
        'price' => 1429,
        //'trade_price' => 'DECIMAL(8,2)',
        //'min_trade_order' => 'SMALLINT UNSIGNED',
        //'meta_title' => 'VARCHAR(100)',
        //'meta_description' => 'TEXT',
        //'meta_keywords' => 'TEXT',
        'created_at' => new CDbException('NOW()'),
        'updated_at' => new CDbException('NOW()'),
        'created_by' => 1,
        'updated_by' => 1,
    ),
    array(
        'product_id' => 3,
        'category_id' => 1,
        'url' => 'ochen-legkiy-perenosnoy-nasos-dlia-pereka4ki-dizelnogo-topliva-krt-24v-40lpm',
        'title' => 'Очень легкий переносной насос для перекачки дизельного топлива KPT, 24В, 40 л/мин',
        //'description' => 'TEXT NOT NULL',
        'price' => 1580,
        //'trade_price' => 'DECIMAL(8,2)',
        //'min_trade_order' => 'SMALLINT UNSIGNED',
        //'meta_title' => 'VARCHAR(100)',
        //'meta_description' => 'TEXT',
        //'meta_keywords' => 'TEXT',
        'created_at' => new CDbException('NOW()'),
        'updated_at' => new CDbException('NOW()'),
        'created_by' => 1,
        'updated_by' => 1,
    ),
);