<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Add' => '',
  'Delte from cart' => '',
  'Remove' => '',
  'Delete' => 'Видалити',
  'Delivery price:' => 'Вартість доставки:',
  'Image' => 'Зображення',
  'In your cart <strong>{n}</strong>' => 'У вашому кошику <strong>{n}</strong>',
  'Make order' => 'Оформити замовлення',
  'Q-ty' => 'Кіль-ть',
  'Resume' => 'Продовжити покупки',
  'Sub-Total:' => 'Ціна за товари:',
  'Summ' => 'Сума',
  'Title' => 'Назва',
  'Total price:' => 'Загальна ціна:',
  'You cart is empty' => 'Ваш кошик порожній',
  'n==1#item|n>1#items' => 'n==0#товарів|n==1#товар|n<5#товари|n>4#товарів',
);
