<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Add product' => '',
  'Edit product' => '',
  'Modules' => '',
  ' Search entire store...' => ' Пошук...',
  '-= Select product =-' => '-= Виберіть товар =-',
  'Add to cart' => 'В кошик',
  'Catalog' => 'Каталог',
  'Categories' => 'Категорії',
  'Category' => 'Категорія',
  'Images' => 'Зображення',
  'Main data' => 'Основні дані',
  'New products' => 'Нові товари',
  'Orders' => 'Замовлення',
  'Products' => 'Товари',
  'This product is already added' => 'Цей товар вже був добавлений',
);
