<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Product "{product}" already exists in this order' => '',
  'Product had not been deleted from order' => '',
  'Product not found' => '',
  'Product succesfully deleted from order' => '',
  'Such product does not exist in current order' => '',
  '-= Select category =-' => '-= Виберіть категорію =-',
  'Add product to order' => 'Добавити товар до замовлення',
  'Create order' => 'Створити замовлення',
  'Decrement' => 'Збільшити',
  'Edit order' => 'Редагувати замовлення',
  'Increment' => 'Зменшити',
  'Number of products' => 'Кіл-ть',
  'Order is alreadey excuted. You cannot change it.' => 'Замовлення вже виконано. Ви не можете його змінювати.',
  'Order not found' => 'Замовлення не знайдено',
  'Order products' => 'Товари',
  'Orders' => 'Замовлення',
  'Product price' => 'Ціна',
  'Save' => 'Зберегти',
  'Save and add products' => 'Зберегти та добавити товари',
  'Subtotal price' => 'Сумма',
  'View order' => 'Подивитись замовлення',
  'You cannot delete executed order' => 'Ви не можете видаляти виконане замовлення',
);
