<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'New user has been created succesfully.' => '',
  'User data had been updated succesfully.' => '',
  'Add user' => 'Новый користувач',
  'Create user' => 'Створити користувача',
  'Edit user' => 'Редагувати користувача',
  'Field "{attribute}" must consist letters and numbers only.' => 'Поле "{attribute}" має складатися тільки з цифр і букв.',
  'New password' => 'Новий пароль',
  'New password confirm' => 'Повторіть новий пароль',
  'Old password' => 'Старий пароль',
  'Old password is incorret.' => 'Старий пароль введено не правильно',
  'Password changed succesfully.' => 'Пароль змінено успішно.',
  'Profile' => 'Мій профіль',
  'Users' => 'Користувачі',
  'Your profile updated succesfully.' => 'Профіль оновлений успішно.',
);
